name = "Moyai the Mods"
author = "fniges, 8ballpizza"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "079c2ec9a0d188afe2d3e0d529462146cc72252efb36614b50f85cd0e2b91440"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21.0"]
datapack-folder = "./config/openloader/packs"
