name = "Moyai the Mods"
author = "fniges, 8ballpizza"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5b8ed753a5ec38e4714a352c10c897bb4a7e12ccccda30c1383e191ca32f505"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
acceptable-game-versions = ["1.21", "1.21.0"]
datapack-folder = "./config/openloader/packs"
