name = "Moyai the Mods"
author = "fniges, 8ballpizza"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b3701c7d1ace0f9d9ed59a7c53ea201bec38654857a8f7c69fc1b1aba2ca5b1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"

[options]
acceptable-game-versions = ["1.21.0"]
