name = "Moyai the Mods"
author = "fniges, 8ballpizza"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c016e23acfd42f4bcbb940c0351490d4c99fd3ae78c72b2e821d5f35402fd840"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.200"

[options]
acceptable-game-versions = ["1.21.0"]
