name = "Moyai the Mods"
author = "fniges, 8ballpizza"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03769736dee3ac3e2972cfc8d8a99d3f554393a280b196f5e94cefe926843b87"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.206"

[options]
acceptable-game-versions = ["1.21", "1.21.0"]
datapack-folder = "./config/openloader/packs"
