# Don't change this! Version used to track needed updates.
version = 1
lowerShield = true
shields = [
    "minecraft:shield",
	"ars_nouveau:enchanters_shield",
	"endermanoverhaul:corrupted_shield",
	"enderscape:end_stone_rubble_shield",
	"enderscape:kurodite_rubble_shield",
	"enderscape:mirestone_rubble_shield",
	"enderscape:veradite_rubble_shield",
	"twilightforest:knightmetal_shield",
	"twilightforest:stronghold_shield"
]
offset = -4.0